# Generated by Django 3.2 on 2023-08-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cameraman_client_order_permission_permissionissuer_phone_token_vacation_vacationkind_weekend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
